(()=>{
const SUPA=window.DUGOUT_CONFIG?.supabaseUrl||'',KEY=window.DUGOUT_CONFIG?.publishableKey||'',PK='dugout-duel-player-token-v2',RK='dugout-duel-room-v3';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state=null,busy=false,story=0,sel={throwBat:'우투우타',position:'IF',arch:'balanced'},drafted=false,room=null,match=null,poll=null,active='career';
const stories=[
 ['SECOND LIFE : BASEBALL','야구장에 있던 순간,\n강한 타구가 내 쪽으로 날아왔다.'],
 ['눈을 뜨니\n<strong>낯선 라커룸.</strong>','유니폼과 이름표가 보인다.\n날짜는 2026년, 고3 마지막 시즌.'],
 ['프로 지명까지\n<strong>12주.</strong>','이 선수의 커리어를 처음부터 시작한다.']
];
const hsEvents=[
 ['첫 평가전','시즌 첫 실전. 감독과 지역 스카우트가 첫 인상을 확인한다.'],['스카우트 방문','복수 구단 관계자가 훈련장과 경기를 지켜본다.'],['주전 경쟁','같은 포지션 경쟁자와 선발 자리를 놓고 경쟁한다.'],['지역 라이벌전','관중이 몰리는 경기. 한 경기의 인상이 크게 남는다.'],['전국대회 예선','패하면 시즌 흐름이 짧아질 수 있는 중요한 일정이다.'],['중간 평가','누적 성적을 기준으로 드래프트 평가가 한 번 정리된다.'],['전국대회 본선','상대 수준이 올라간다. 실전 대응력이 중요하다.'],['구단 인터뷰','경기 전 구단 관계자와 짧은 면담이 잡혔다.'],['상위 지명 경쟁','비슷한 평가의 선수들과 순번 경쟁이 시작된다.'],['집중 관찰 경기','여러 구단이 같은 경기를 확인한다.'],['최종 쇼케이스','드래프트 전 마지막 공개 평가전이다.'],['드래프트 직전','고교 마지막 일정. 다음은 지명 결과다.']
];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){$$('.screen').forEach(x=>x.classList.remove('on'));$('#'+id)?.classList.add('on');active=id;$('#tabs')?.classList.toggle('show',['career','profile','rival'].includes(id));$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));if(id!=='rival')stopPoll();window.scrollTo(0,0)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1500)}
async function rpc(name,body,ms=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(`${SUPA}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal});const tx=await r.text();let d;try{d=tx?JSON.parse(tx):null}catch{d=tx}if(!r.ok)throw new Error(d?.message||String(d||r.status));return d}finally{clearTimeout(t)}}
const token=()=>localStorage.getItem(PK)||'';
function avg(st){const pa=+st?.pa||0,h=+st?.h||0;return pa?(h/pa).toFixed(3).replace(/^0/,''):'.000'}
function pitcher(p){return String(p?.position||'').toUpperCase()==='P'}
function grade(p){const s=+p.scoutInterest||0,w=+(p.seasonStats?.war||0);if(s>=78||w>=7)return'A';if(s>=55||w>=4)return'B+';if(s>=35||w>=2)return'B';return'C+'}
function renderStory(){const s=stories[Math.min(story,2)];$('#storyEyebrow').textContent=s[0];$('#storyTitle').innerHTML=s[1].split('\n')[0].includes('<strong>')?s[1].split('\n')[0]:story===0?'이번 생도\n<strong>야구.</strong>':s[1].split('\n')[0];if(story===0){$('#storyTitle').innerHTML='이번 생도<br><strong>야구.</strong>';$('#storyCopy').textContent=s[1]}else{$('#storyTitle').innerHTML=s[1].replace('\n','<br>');$('#storyCopy').textContent=story===1?'유니폼과 이름표가 보인다.\n날짜는 2026년, 고3 마지막 시즌.':'이 선수의 커리어를 처음부터 시작한다.'}$('#storyNext').textContent=story===2?'선수 생성':'계속'}
function bindChoice(root,key,after){$$(root+' .choice').forEach(b=>b.onclick=()=>{$$(root+' .choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');sel[key]=b.dataset.v;after?.()})}
function renderStyles(){const isP=sel.position==='P';const data=isP?[
 ['balanced','밸런스형','구위와 제구를 고르게 가져갑니다.','구속 58 · 제구 58\n변화 57 · 체력 60'],['velocity','구위형','빠른 공과 탈삼진 능력에 집중합니다.','구속 70 · 제구 50\n변화 55 · 체력 60'],['control','제구형','볼넷을 줄이고 경기 운영을 안정시킵니다.','구속 54 · 제구 70\n변화 58 · IQ 64'],['breaking','변화구형','결정구와 헛스윙 유도 능력이 강점입니다.','구속 55 · 제구 57\n변화 71 · IQ 61']
]:[
 ['balanced','밸런스형','공수 전반에 큰 약점이 없습니다.','CON 56 · POW 56\nSPD 56 · DEF 56'],['contact','교타형','컨택과 출루 안정성이 강점입니다.','CON 68 · POW 44\nDISC 60 · DEF 63'],['slugger','장타형','장타 생산력을 최우선으로 둡니다.','CON 49 · POW 72\nSPD 43 · DEF 49'],['speed','스피드형','주루와 넓은 수비 범위가 강점입니다.','CON 61 · POW 44\nSPD 74 · DEF 62']
];
if(!data.some(x=>x[0]===sel.arch))sel.arch='balanced';$('#styleList').innerHTML=data.map(x=>`<button type="button" class="style ${sel.arch===x[0]?'active':''}" data-v="${x[0]}"><div><h3>${x[1]}</h3><p>${x[2]}</p></div><div class="nums">${x[3].replace('\n','<br>')}</div></button>`).join('');$$('#styleList .style').forEach(b=>b.onclick=()=>{sel.arch=b.dataset.v;$$('#styleList .style').forEach(x=>x.classList.toggle('active',x===b))})}
function payload(){const base={name:$('#name').value.trim(),number:+$('#number').value||7,throwBat:sel.throwBat,position:sel.position,wishTeam:$('#team').value||'서울 블레이즈',school:'고교',origin:'대한민국',height:178,weight:75,archetype:sel.arch};if(sel.position==='P'){return Object.assign(base,sel.arch==='velocity'?{velocity:70,command:50,breaking:55,stamina:60,pitchIQ:55}:sel.arch==='control'?{velocity:54,command:70,breaking:58,stamina:58,pitchIQ:64}:sel.arch==='breaking'?{velocity:55,command:57,breaking:71,stamina:58,pitchIQ:61}:{velocity:58,command:58,breaking:57,stamina:60,pitchIQ:58})}return Object.assign(base,sel.arch==='contact'?{contact:68,power:44,discipline:60,speed:57,defense:63}:sel.arch==='slugger'?{contact:49,power:72,discipline:53,speed:43,defense:49}:sel.arch==='speed'?{contact:61,power:44,discipline:54,speed:74,defense:62}:{contact:56,power:56,discipline:56,speed:56,defense:56})}
function statTop(p){const st=p.seasonStats||{};if(pitcher(p))return[['ERA',(+st.era||0).toFixed(2)],['WHIP',(+st.whip||0).toFixed(2)],['K',+st.k||0],['WAR',(+st.war||0).toFixed(2)]];return[['AVG',avg(st)],['HR',+st.hr||0],['RBI',+st.rbi||0],['WAR',(+st.war||0).toFixed(2)]]}
function careerChoices(p){if(pitcher(p))return[['contact','제구 훈련','볼넷을 줄이고 스트라이크 비율을 높인다.'],['power','구위 훈련','직구 구속과 탈삼진 능력을 끌어올린다.'],['discipline','변화구 훈련','결정구 완성도를 높인다.'],['speed','체력 훈련','긴 이닝을 버틸 수 있게 준비한다.'],['recovery','회복','피로와 컨디션을 관리한다.']];return[['contact','컨택 훈련','정확한 타격과 안타 생산에 집중한다.'],['power','장타 훈련','강한 타구와 장타 생산에 집중한다.'],['discipline','선구 훈련','볼 판별과 출루 능력을 끌어올린다.'],['speed','주루·수비','경기 기여 범위를 넓힌다.'],['recovery','회복','피로와 컨디션을 관리한다.']]}
function renderCareer(){const p=state.player,w=+state.week||1,hs=p.stage==='HIGH_SCHOOL';$('#stage').textContent=hs?'HIGH SCHOOL · FINAL SEASON':`${p.team||p.wishTeam} · PRO`;$('#careerTitle').textContent=hs?'고3 마지막 시즌':`프로 ${p.proYear||1}년차`;$('#season').textContent=`SEASON ${state.season}`;$('#week').textContent=`WEEK ${w} / 12`;$('#progress').innerHTML=Array.from({length:12},(_,i)=>`<i class="${i+1<w?'done':i+1===w?'now':''}"></i>`).join('');$('#playerstrip').innerHTML=`<div><div class="pname">${esc(p.name)}</div><div class="pmeta">#${p.number} · ${esc(p.position)} · ${esc(p.throwBat)} · ${esc(p.role||'주전 경쟁')}<br>${esc(p.team||'고교')} · 희망 ${esc(p.wishTeam||'')}</div><div class="quickstats">${statTop(p).map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div></div><div class="grade"><small>SCOUT</small><b>${grade(p)}</b></div>`;const ev=hs?hsEvents[w-1]||hsEvents[11]:[`정규시즌 ${w}주`,`프로 시즌 일정이 이어진다. 현재 역할과 컨디션에 맞춰 한 주를 준비한다.`];$('#scene').innerHTML=`<div class="num">${hs?'WEEK '+w:'PRO WEEK '+w}</div><h2>${esc(ev[0])}</h2><p>${esc(ev[1])}</p><div class="sceneinfo"><span class="tag">폼 ${+p.form||0}</span><span class="tag">피로 ${+p.fatigue||0}</span><span class="tag">감독 신뢰 ${+p.managerTrust||0}</span><span class="tag">스카우트 ${+p.scoutInterest||0}</span></div><div class="decisiontitle">이번 주 선택</div><div class="decisions">${careerChoices(p).map(c=>`<button class="decision" data-action="${c[0]}"><b>${c[1]}</b><span>${c[2]}</span></button>`).join('')}</div>`;$$('[data-action]').forEach(b=>b.onclick=()=>advance(b.dataset.action));renderProfile()}
async function advance(action){if(busy)return;busy=true;$$('[data-action]').forEach(x=>x.disabled=true);const before=JSON.parse(JSON.stringify(state));try{state=await rpc('dugout_solo_action',{p_token:token(),p_action:action});drafted=before.player.stage==='HIGH_SCHOOL'&&state.player.stage==='PRO';renderResult(state.player);show('result')}catch(e){toast('진행 실패 · '+e.message);renderCareer()}finally{busy=false}}
function renderResult(p){const l=p.lastWeek||{};const stats=pitcher(p)?[['IP',(+l.ip||0).toFixed(1)],['ER',+l.er||0],['K',+l.k||0],['ERA',(+l.era||0).toFixed(2)]]:[['PA',+l.pa||0],['H',+l.h||0],['HR',+l.hr||0],['WAR',(+l.war||0).toFixed(2)]];$('#resultBody').innerHTML=`<div class="eyebrow">WEEK RESULT</div><h1>${esc(p.lastEvent?.title||'주간 결과')}</h1><div class="resultstats">${stats.map(x=>`<div class="resultstat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><div class="resultmsg"><b>${esc(p.lastEvent?.title||'')}</b><p>${esc(p.lastEvent?.body||'')}</p></div><button id="nextResult" class="primary">${drafted?'드래프트 결과':'다음 주'}</button>`;$('#nextResult').onclick=()=>{if(drafted){renderDraft();show('draft')}else{renderCareer();show('career')}}}
function renderDraft(){const p=state.player;$('#draftPick').textContent=p.draft||'육성선수';$('#draftTeam').textContent=p.team||p.wishTeam;$('#draftName').textContent=`${p.name} · ${p.position}`}
function renderProfile(){if(!state)return;const p=state.player,st=p.careerStats||{},attrs=pitcher(p)?[['구속',p.velocity],['제구',p.command],['변화구',p.breaking],['체력',p.stamina],['투구 IQ',p.pitchIQ]]:[['컨택',p.contact],['장타',p.power],['선구',p.discipline],['주루',p.speed],['수비',p.defense]];$('#profileContent').innerHTML=`<div class="eyebrow">PLAYER PROFILE</div><h1>${esc(p.name)}</h1><div class="profileline"><span>포지션</span><b>${esc(p.position)}</b></div><div class="profileline"><span>투타</span><b>${esc(p.throwBat)}</b></div><div class="profileline"><span>현재 소속</span><b>${esc(p.team||'고교')}</b></div><div class="profileline"><span>드래프트</span><b>${esc(p.draft||'미정')}</b></div><div class="profileline"><span>통산 WAR</span><b>${(+st.war||0).toFixed(2)}</b></div><div class="profileline"><span>온라인</span><b>${+p.duelWins||0}승 ${+p.duelLosses||0}패</b></div><div class="attrs">${attrs.map(x=>`<div class="attr"><span>${x[0]}</span><div class="bar"><i style="width:${Math.min(100,+x[1]||0)}%"></i></div><b>${+x[1]||0}</b></div>`).join('')}</div><button id="unlink" class="danger" style="margin-top:22px">이 기기 선수 연결 해제</button>`;$('#unlink').onclick=()=>{if(confirm('이 기기에서 선수 연결을 해제할까요? 서버 기록은 유지됩니다.')){localStorage.removeItem(PK);localStorage.removeItem(RK);location.reload()}}}
function loadRoom(){try{return JSON.parse(localStorage.getItem(RK)||'null')}catch{return null}}function saveRoom(x){room=x;localStorage.setItem(RK,JSON.stringify(x))}function clearRoom(){room=null;match=null;localStorage.removeItem(RK);stopPoll()}
function renderLobby(){room=loadRoom();$('#rivalContent').innerHTML=`<div class="eyebrow">ONLINE</div><h1>라이벌 경기</h1><p style="font-size:12px;color:#7e858b;line-height:1.6">커리어와 분리된 2인 비공개 경기입니다.</p><div class="section"><button id="host" class="primary">비공개 경기 생성</button></div><div class="section"><div class="join"><input id="joinCode" maxlength="10" placeholder="ROOM CODE"><button id="join">입장</button></div></div>${room?`<div class="section"><div class="roomcode">${esc(room.code)}</div><button id="resume" class="secondary" style="margin-top:8px">이어하기</button></div>`:''}`;$('#host').onclick=hostRoom;$('#join').onclick=()=>joinRoom($('#joinCode').value);if($('#resume'))$('#resume').onclick=openRoom}
async function hostRoom(){try{const d=await rpc('dugout_create_room_v2',{p_player_token:token()});saveRoom({code:d.code,roomToken:d.roomToken});openRoom()}catch(e){toast('룸 생성 실패')}}async function joinRoom(code){code=String(code||'').trim().toUpperCase();if(!code)return;try{const d=await rpc('dugout_join_room_v2',{p_code:code,p_player_token:token()});saveRoom({code:d.code,roomToken:d.roomToken});openRoom()}catch(e){toast('입장 실패 · '+e.message)}}
async function openRoom(){room=loadRoom();if(!room)return renderLobby();$('#rivalContent').innerHTML='<div class="wait"><div class="eyebrow">MATCH</div><h2>경기 상태 확인 중</h2></div>';try{const r=await rpc('dugout_get_room_v2',{p_code:room.code,p_room_token:room.roomToken});if(!r.guest){$('#rivalContent').innerHTML=`<div class="wait"><div class="eyebrow">PRIVATE ROOM</div><div class="roomcode">${esc(room.code)}</div><h2>상대 입장 대기</h2><button id="leave" class="secondary">룸 나가기</button></div>`;$('#leave').onclick=()=>{clearRoom();renderLobby()};startPoll('room');return}match=await rpc('dugout_start_match_v1',{p_code:room.code,p_room_token:room.roomToken});renderMatch();startPoll('match')}catch(e){toast('경기 불러오기 실패')}}
function outcome(x){return({OUT:'아웃',BB:'볼넷','1B':'안타','2B':'2루타','3B':'3루타',HR:'홈런',SAC:'희생타'})[x]||x||''}
function renderMatch(){if(!match)return;const h=match.host||{},g=match.guest||{},bat=match.myRole==='bat',ready=bat?match.offenseReady:match.defenseReady;$('#rivalContent').innerHTML=`<div class="scoreboard"><div class="inning">${match.inning}회 ${match.half==='top'?'초':'말'} · ${match.outs} OUT</div><div class="scoreline"><b>${esc(g.team||g.wishTeam||'AWAY')} · ${esc(g.name||'')}</b><strong>${match.guestScore}</strong></div><div class="scoreline"><b>${esc(h.team||h.wishTeam||'HOME')} · ${esc(h.name||'')}</b><strong>${match.hostScore}</strong></div></div>${match.phase==='finished'?`<div class="wait"><div class="eyebrow">FINAL</div><h2>${match.guestScore} : ${match.hostScore}</h2><button id="closeMatch" class="secondary">룸 닫기</button></div>`:`<div class="section"><div class="eyebrow">${bat?'BATTING':'DEFENSE'}</div><h2 style="font-size:25px;margin:7px 0">${ready?'상대 선택 대기':'선택'}</h2>${ready?'':`<div class="matchchoices">${(bat?[['contact','컨택','안타 확률 우선'],['power','강공','장타 확률 우선'],['patient','기다리기','볼넷과 좋은 공을 기다림'],['situational','진루타','주자 진루를 우선']]:[['challenge','정면승부','빠른 승부'],['chase','유인구','범타와 헛스윙 유도'],['suppress','장타 억제','큰 타구를 막음'],['pitcharound','승부 회피','강한 타자를 피함']]).map(o=>`<button class="matchchoice" data-mc="${o[0]}"><b>${o[1]}</b><span>${o[2]}</span></button>`).join('')}</div>`}</div>`}${match.lastPlay?`<div class="section"><b style="font-size:11px">최근 결과 · ${outcome(match.lastPlay.outcome)}</b></div>`:''}`;$$('[data-mc]').forEach(b=>b.onclick=()=>submitMatch(b.dataset.mc));if($('#closeMatch'))$('#closeMatch').onclick=()=>{clearRoom();renderLobby()}}
async function submitMatch(choice){if(busy)return;busy=true;try{match=await rpc('dugout_submit_match_choice_v1',{p_code:room.code,p_room_token:room.roomToken,p_choice:choice});renderMatch()}catch(e){toast('선택 실패')}finally{busy=false}}
function startPoll(mode){stopPoll();const tick=async()=>{if(active!=='rival'||!room)return;try{if(mode==='room'){const r=await rpc('dugout_get_room_v2',{p_code:room.code,p_room_token:room.roomToken},4000);if(r.guest){match=await rpc('dugout_start_match_v1',{p_code:room.code,p_room_token:room.roomToken},4000);renderMatch();mode='match'}}else{match=await rpc('dugout_get_match_v1',{p_code:room.code,p_room_token:room.roomToken},4000);renderMatch()}}catch{}poll=setTimeout(tick,1400)};poll=setTimeout(tick,1400)}function stopPoll(){if(poll){clearTimeout(poll);poll=null}}
$('#storyNext').onclick=()=>{if(story<2){story++;renderStory()}else show('create1')};$('#storySkip').onclick=()=>show('create1');$('#name').oninput=e=>$('#nameCount').textContent=e.target.value.length+'/16';bindChoice('#throwChoices','throwBat');bindChoice('#posChoices','position');$('#create1Form').onsubmit=e=>{e.preventDefault();if(!$('#name').value.trim())return;renderStyles();show('create2')};$('#back1').onclick=()=>show('create1');$('#createPlayer').onclick=async()=>{if(busy)return;busy=true;$('#createError').textContent='';try{const d=await rpc('dugout_create_player',{p_player:payload()});localStorage.setItem(PK,d.token);state={player:d.player,season:d.season,week:d.week};renderCareer();show('career')}catch(e){$('#createError').textContent='선수 생성 실패 · '+e.message}finally{busy=false}};$('#draftContinue').onclick=()=>{renderCareer();show('career')};$$('#tabs button').forEach(b=>b.onclick=()=>{const t=b.dataset.tab;if(t==='career'){renderCareer();show('career')}else if(t==='profile'){renderProfile();show('profile')}else{renderLobby();show('rival');if(loadRoom())setTimeout(openRoom,0)}});
async function boot(){renderStory();const t=token();if(!t)return show('intro');try{state=await rpc('dugout_get_player',{p_token:t},4000);if(!state?.player)throw 0;renderCareer();show('career')}catch{localStorage.removeItem(PK);localStorage.removeItem(RK);show('intro')}}boot();
})();