(()=>{'use strict';const L=window.LIFE,$=L.$,$$=L.$$;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1500)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('on'));$('#'+id).classList.add('on');$('#tabs').classList.toggle('show',['career','history','player'].includes(id));$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$('#topMeta').textContent=id==='career'&&L.state?`${L.state.year} · ${L.stage(L.state)}`:id==='history'?'CAREER LOG':id==='player'?'PLAYER':'BASEBALL CAREER';window.scrollTo(0,0)}
function home(){const x=L.legacy();$('#resumeCareer').hidden=!L.token();$('#legacyPreview').innerHTML=x.careers?`<div class="legacy-card"><div><small>완주한 커리어</small><b>${x.careers}</b></div><div style="text-align:right"><small>최고 명예점수</small><b>${x.hof.toLocaleString()}</b></div></div>`:''}
function ladder(){const s=L.state,i=s.stage==='HIGH_SCHOOL'?0:s.stage==='MINORS'?2:s.flags.star?4:3;return['고교','드래프트','2군','1군','스타'].map((x,n)=>`<i class="ladder-step ${n<i?'done':n===i?'now':''}" title="${x}"></i>`).join('')}
function render(){const s=L.state,m=L.moment();$('#stage').textContent=`${L.stage(s)} · ${s.year}`;$('#careerTitle').textContent=s.stage==='HIGH_SCHOOL'?'고3 마지막 시즌':s.stage==='MINORS'?'1군 콜업 경쟁':s.flags.star?'리그의 중심':'1군에서 살아남기';$('#age').textContent=s.age;$('#identity').innerHTML=`<div><div class="id-name">${L.esc(s.name)}</div><div class="id-meta">#${s.number} · ${L.esc(s.position)} · OVR ${L.ov(s)}<br>${L.esc(s.team)} · ${L.esc(s.styleLabel)}</div></div><div class="id-role"><small>ROLE</small><b>${L.esc(L.role(s))}</b></div>`;$('#ladder').innerHTML=ladder();$('#moment').innerHTML=`<div class="moment-top"><span class="moment-type">${m.type}</span><span class="moment-stakes">MOMENT ${s.momentIndex+1} / ${s.seasonMoments}</span></div><h2>${L.esc(m.title)}</h2><p>${L.esc(m.body)}</p><div class="score-situation"><div><span>SITUATION</span><b>${L.esc(m.sit)}</b></div><span>${L.esc(s.goals.next)}</span></div><div class="choice-title">어떻게 할까</div><div class="career-choices">${m.choices.map(c=>`<button class="career-choice ${c.risk}" data-c="${c.id}"><b>${L.esc(c.t)}</b><span>${L.esc(c.b)}</span><em>${L.esc(c.stake)}</em></button>`).join('')}</div>`;$$('[data-c]').forEach(b=>b.onclick=()=>choose(b.dataset.c,m));stats();meters();traits();history();player()}
function stats(){const s=L.state,st=s.seasonStats;$('#seasonMeta').textContent=`${s.year} · ${L.stage(s)}`;$('#seasonStats').innerHTML=[['AVG',L.avg(st)],['HR',st.hr],['RBI',st.rbi],['SB',st.sb],['WAR',(+st.war).toFixed(2)]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function meters(){const s=L.state;$('#meters').innerHTML=[['감독 신뢰',s.coach],['평판',s.reputation],['컨디션',s.health],['피로 여유',100-s.fatigue]].map(x=>`<div><div class="meter-top"><span>${x[0]}</span><b>${Math.round(x[1])}</b></div><div class="bar"><i style="width:${L.clamp(x[1],0,100)}%"></i></div></div>`).join('')}
function traits(){const a=L.state.traits;$('#traitList').innerHTML=a.map((x,i)=>`<span class="trait ${i>2?'rare':''}">${L.esc(x)}</span>`).join('')}
function history(){const s=L.state;$('#historyBody').innerHTML=[...s.history].reverse().map(h=>`<div class="history-year"><div class="history-year-head"><b>${h.year} · ${L.esc(h.stage)}</b><span>${L.esc(h.team)}</span></div><p>${L.esc(h.summary)}<br>AVG ${L.avg(h.stats)} · HR ${h.stats.hr} · WAR ${(+h.stats.war).toFixed(2)}</p></div>`).join('')+`<div class="history-year"><div class="history-year-head"><b>${s.year} · 진행 중</b><span>${L.esc(s.team)}</span></div><p>${L.esc(s.role)} · ${s.momentIndex}/${s.seasonMoments} 모먼트</p></div>`}
function player(){const s=L.state,a=s.attrs;$('#playerBody').innerHTML=`<div class="profile-card"><div class="eyebrow">PLAYER PROFILE</div><h1 class="profile-name">${L.esc(s.name)}</h1><div class="profile-sub">#${s.number} · ${L.esc(s.position)} · ${L.esc(s.team)} · AGE ${s.age}</div><div style="margin-top:18px">${[['CON',a.contact],['POW',a.power],['DISC',a.discipline],['SPD',a.speed],['DEF',a.defense]].map(x=>`<div class="attr-row"><span>${x[0]}</span><div class="bar"><i style="width:${x[1]}%"></i></div><b>${x[1]}</b></div>`).join('')}</div><div style="margin-top:15px"><div class="profile-line"><span>역할</span><b>${L.esc(s.role)}</b></div><div class="profile-line"><span>계약</span><b>${s.contract?`${s.contract.years}년 · ${s.contract.salary.toLocaleString()}만`:'—'}</b></div><div class="profile-line"><span>팬</span><b>${Math.round(s.fans).toLocaleString()}</b></div><div class="profile-line"><span>시장 가치</span><b>${Math.round(s.market).toLocaleString()}만</b></div><div class="profile-line"><span>통산 WAR</span><b>${(+s.careerStats.war).toFixed(2)}</b></div><div class="profile-line"><span>라이벌</span><b>${L.esc(s.rival.name)} · REP ${Math.round(s.rival.rep)}</b></div></div><button id="unlinkCareer" class="danger" style="margin-top:20px">이 기기 연결 해제</button></div>`;$('#unlinkCareer').onclick=()=>{if(confirm('이 기기에서 현재 커리어 연결만 해제할까요?')){localStorage.removeItem(L.TK);L.state=null;home();show('home')}}}
function choose(id,m){if(L.busy)return;L.busy=true;const before={coach:L.state.coach,reputation:L.state.reputation,health:L.state.health,ov:L.ov()};const r=L.simulate(id,m);L.apply(r);L.state.momentIndex++;result(r,before,L.state.momentIndex>=L.state.seasonMoments);L.persist().finally(()=>L.busy=false);show('result')}
function result(r,b,end){const s=L.state,d=[['감독',Math.round(s.coach-b.coach)],['평판',Math.round(s.reputation-b.reputation)],['컨디션',Math.round(s.health-b.health)],['OVR',L.ov()-b.ov]];$('#resultBody').innerHTML=`<div class="result-kicker">${r.tone==='good'?'MOMENT WON':r.tone==='bad'?'MOMENT LOST':'CAREER UPDATE'}</div><h1>${L.esc(r.title)}</h1><div class="big-result"><b>${L.esc(r.body)}</b><p>이 결과는 시즌과 다음 역할에 누적된다.</p></div><div class="delta-row">${d.map(x=>`<div class="delta ${x[1]>0?'up':x[1]<0?'down':''}"><small>${x[0]}</small><b>${x[1]>0?'+':''}${x[1]}</b></div>`).join('')}</div>${r.stats.pa?`<div class="section compact-section"><div class="stats-grid"><div class="stat"><small>PA</small><b>${r.stats.pa}</b></div><div class="stat"><small>H</small><b>${r.stats.h}</b></div><div class="stat"><small>HR</small><b>${r.stats.hr}</b></div><div class="stat"><small>RBI</small><b>${r.stats.rbi}</b></div><div class="stat"><small>WAR</small><b>${(+r.stats.war).toFixed(2)}</b></div></div></div>`:''}<div class="result-actions"><button id="resultNext" class="primary">${end?'시즌 결과 보기':'다음 모먼트'}</button></div>`;$('#resultNext').onclick=()=>end?seasonEnd():(render(),show('career'))}
function seasonEnd(){const sum=L.summary(),s=L.state,st=s.seasonStats;$('#summaryBody').innerHTML=`<div class="result-kicker">SEASON ${s.year}</div><h1>${L.esc(sum.headline)}</h1><div class="summary-hero"><small>${L.esc(s.team)} · ${L.esc(s.role)}</small><b>WAR ${(+st.war).toFixed(2)}</b></div><div class="stats-grid"><div class="stat"><small>AVG</small><b>${L.avg(st)}</b></div><div class="stat"><small>HR</small><b>${st.hr}</b></div><div class="stat"><small>RBI</small><b>${st.rbi}</b></div><div class="stat"><small>SB</small><b>${st.sb}</b></div><div class="stat"><small>REP</small><b>${Math.round(s.reputation)}</b></div></div><div class="big-result"><b>${L.esc(sum.text)}</b><p>${sum.aw.length?'획득 · '+sum.aw.join(' / '):'다음 역할과 계약이 이 시즌으로 결정된다.'}</p></div><div id="summaryActions" class="result-actions"></div>`;summaryActions(sum);L.persist();show('seasonEnd')}
function summaryActions(sum){const box=$('#summaryActions'),s=L.state;if(sum.next==='DRAFT'){const teams=[...L.TEAMS].sort(()=>Math.random()-.5).slice(0,3);box.innerHTML=teams.map((t,i)=>`<button class="offer" data-team="${L.esc(t)}"><b>${L.esc(t)}</b><span>${i===0?'가장 높은 평가를 준 구단':'성장 계획이 좋은 구단'}</span><strong>${L.esc(s.draft)}</strong></button>`).join('');$$('[data-team]').forEach(b=>b.onclick=()=>draft(b.dataset.team))}else if(sum.next==='FA'){const offers=[...L.TEAMS].sort(()=>Math.random()-.5).slice(0,3).map((team,i)=>({team,years:L.int(2,5),salary:Math.round((L.ov()*170+s.reputation*120+s.careerStats.war*220)*(1+L.rnd(-.08,.14))/100)*100,role:i?'클린업 경쟁':'주전 보장'}));box.innerHTML=offers.map((o,i)=>`<button class="offer" data-o="${i}"><b>${L.esc(o.team)}</b><span>${o.role} · ${o.years}년</span><strong>${o.salary.toLocaleString()}만 / 년</strong></button>`).join('');$$('[data-o]').forEach(b=>b.onclick=()=>fa(offers[+b.dataset.o]))}else{box.innerHTML=`<button id="nextYear" class="primary">${sum.next==='CALL_UP'?'1군 시즌 시작':sum.next==='MINORS'?'2군에서 다시 도전':'다음 시즌'}</button>`;$('#nextYear').onclick=()=>next(sum.next)}}
function draft(team){const s=L.state;s.flags.drafted=true;s.team=team;s.stage='MINORS';s.roleIndex=1;s.role=L.ROLES[1];s.contract={years:3,salary:s.draft.includes('TOP')?7000:s.draft.includes('1라운드')?5000:s.draft.includes('2~3')?3200:1800};s.coach=35;s.reputation=L.clamp(s.reputation+5,0,100);s.goals={season:'1군 콜업',next:'2군 주전 자리 확보'};L.nextYear();render();show('career')}
function next(type){const s=L.state;if(type==='CALL_UP'){s.stage='PRO';s.flags.firstTeam=true;s.roleIndex=Math.max(3,s.roleIndex);s.role=L.ROLES[s.roleIndex];s.coach=40;s.goals={season:'1군 정착',next:'주전 경쟁'}}else if(type==='MINORS'){s.stage='MINORS';s.goals={season:'1군 콜업',next:'2군 성적 폭발'}}else{s.stage='PRO';s.goals={season:s.flags.star?'우승 / MVP':'주전 확보',next:s.flags.star?'포스트시즌 지배':'출전기회 확보'}}L.nextYear();if(s.retired){retired();show('retired')}else{render();show('career')}}
function fa(o){const s=L.state;s.team=o.team;s.contract={years:o.years,salary:o.salary};s.flags.fa=true;s.roleIndex=Math.max(s.roleIndex,o.role.includes('클린업')?6:5);s.role=L.ROLES[s.roleIndex];s.coach=50;L.nextYear();render();show('career')}
function retired(){const s=L.state;$('#retiredBody').innerHTML=`<div class="hall">CAREER COMPLETE</div><h1>${L.esc(s.name)}</h1><div class="retired-score">${s.score.toLocaleString()}</div><p>명예 점수<br>${s.age-18}년 커리어 · 통산 WAR ${(+s.careerStats.war).toFixed(2)} · ${s.awards.length}개 주요 수상</p><button id="newAfter" class="primary" style="margin-top:18px">새 선수 시작</button>`;$('#newAfter').onclick=async()=>{try{await L.rpc('dugout_life_delete_v1',{p_token:L.token()})}catch{}localStorage.removeItem(L.TK);L.state=null;home();show('home')}}
async function create(e){e.preventDefault();if(L.busy)return;const name=$('#name').value.trim();if(!name)return;L.busy=true;$('#createBtn').disabled=true;L.state=L.fresh(name,+$('#number').value||7,L.sel.position,L.sel.style);try{const d=await L.rpc('dugout_life_create_v1',{p_state:L.state});localStorage.setItem(L.TK,d.token);L.state=d.state;render();show('career')}catch(err){L.state=null;$('#createError').textContent='커리어 생성 실패 · '+err.message}finally{L.busy=false;$('#createBtn').disabled=false}}
async function resume(){try{const d=await L.rpc('dugout_life_get_v1',{p_token:L.token()},4500);L.state=d.state;if(L.state.retired){retired();show('retired')}else{render();show('career')}}catch{toast('저장된 커리어를 불러오지 못했습니다.');localStorage.removeItem(L.TK);home()}}
function bind(root,key){$$(root+' [data-v]').forEach(b=>b.onclick=()=>{$$(root+' [data-v]').forEach(x=>x.classList.toggle('active',x===b));L.sel[key]=b.dataset.v})}
$('#newCareer').onclick=()=>show('create');$('#resumeCareer').onclick=resume;$('#createForm').onsubmit=create;bind('#posChoices','position');bind('#styleChoices','style');$$('#tabs button').forEach(b=>b.onclick=()=>{const t=b.dataset.tab;if(t==='career'){render();show('career')}if(t==='history'){history();show('history')}if(t==='player'){player();show('player')}});home();if(L.token())$('#resumeCareer').hidden=false;
})();
